{
  "ERROR_ACCESSING_OPENAI_API_KEY": "HIBA a OpenAI API-hoz val√≥ csatlakoz√°s k√∂zben. K√©rj√ºk, ellen≈ërizze az API-kulcsot, vagy pr√≥b√°lja meg k√©s≈ëbb.",
  "ERROR_ADDING_ADDITIONAL_TASKS": "HIBA a tov√°bbi feladat(ok) hozz√°ad√°sa k√∂zben. Lehet, hogy a modell√ºnk nem tudja kezelni a v√°laszt √©s az eredm√©nyezte ezt. Folytat√°s...",
  "RATE_LIMIT_EXCEEDED": "El√©rte a maxim√°lis lek√©rdez√©sek sz√°m√°t! K√©rj√ºk, lass√≠tson le...üòÖ",
  "AGENT_MAXED_OUT_LOOPS": "Ez az √ºgyn√∂k el√©rte a maxim√°lis futtathat√≥ k√∂reinek a sz√°m√°t. Hogy megmentse a p√©nzt√°rc√°j√°t, ez az √ºgyn√∂k most le√°ll... Az √ºgyn√∂k fut√°si k√∂reinek a maxim√°lis sz√°m√°t az be√°ll√≠t√°sokban lehet konfigur√°lni.",
  "DEMO_LOOPS_REACHED": "Sajn√°ljuk, de mivel ez egy bemutat√≥ alkalmaz√°s √≠gy nem tudjuk t√∫l hossz√∫ ideig futtatni az √ºgyn√∂keit. Megjegyz√©s: ha hosszabb futtat√°sokat szeretne, k√©rj√ºk, adjon meg egy saj√°t API-kulcsot a Be√°ll√≠t√°sokban. Le√°ll√≠t√°s...",
  "AGENT_MANUALLY_SHUT_DOWN": "Az √ºgyn√∂k manu√°lisan le√°ll√≠tva.",
  "ALL_TASKS_COMPLETETD": "Minden feladat befejez≈ëd√∂tt. Le√°ll√≠t√°s...",
  "ERROR_API_KEY_QUOTA": "HIBA az OpenAI API-kulcs haszn√°latakor. T√∫ll√©pte jelenlegi kv√≥t√°j√°t, k√©rj√ºk, ellen≈ërizze sz√°ml√°z√°si adatait.",
  "ERROR_OPENAI_API_KEY_NO_GPT4": "HIBA: Az √ñn OpenAI API kulcsa nem rendelkezik GPT-4 hozz√°f√©r√©ssel. El≈ësz√∂r jelentkeznie kell az OpenAI v√°r√≥list√°j√°n. (Ez elt√©r a ChatGPT Plus-t√≥l)",
  "ERROR_RETRIEVE_INITIAL_TASKS": "HIBA az alapfeladatok lek√©rdez√©se k√∂zben. Pr√≥b√°lja √∫jra, fogalmazza meg az √ºgyn√∂k c√©lj√°t vil√°gosabban, vagy m√≥dos√≠tsa a oly m√≥don, hogy az megfeleljen a modell√ºnk sz√°m√°ra. Le√°ll√≠t√°s...",
  "INVALID_OPENAI_API_KEY": "HIBA √©rv√©nytelen OpenAI API-kulcs"
}
